### ISSUE TITLE
Heroku says: Source code violates the Salesforce Acceptable Use 

### ISSUE THREAD

**Issue by xx5244** [Sallat-M/FileToLink#2]
When I try to deploy app, I see message: Item could not be created: We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy
![圖片 3](https://user-images.githubusercontent.com/66669376/154363275-8510db21-264d-40e9-a9b5-af455ef1c853.png)

**Comment by chookg** [comment]
你可以fork一份，然后改个名字，再部署就可以了
